# The OS X Build Environment
# https://docs.travis-ci.com/user/reference/osx/#Xcode-version

language: objective-c
xcode_project: RxGRDB.xcodeproj

# Caches
cache:
    - bundler
    - cocoapods

# Custom CocoaPods installation
install:
    - bundle install
    - bundle exec pod repo update
  
# Disable the default Travis-CI submodule logic
# The various make commands ensure that the appropriate submodules are retrieved
git:
  submodules: false

jobs:
  include:

    - stage: Test Xcode 13.1
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode13.1
      env:
        - TID=RxGRDB [SPM] (macOS)
      script: make test_SPM
    
    - stage: Test Xcode 13.1
      gemfile: .ci/gemfiles/Gemfile.travis
      osx_image: xcode13.1
      env:
        - TID=CocoaPods Lint
      script: make test_CocoaPodsLint
